version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: ./Dockerfile.app
    ports:
      - "5000:5000"
  
  testweb:
    build:
      context: ..
      dockerfile: ./Dockerfile.test